[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ['-Clink-arg=-Tsrc/riscv/qemu-virt.ld']

[target.riscv64gc-unknown-none-elf]
runner = """qemu-system-riscv64 -machine virt -cpu rv64
                              -smp 4 -m 128M
                              -drive file=tedos-fs.img,if=none,format=raw,id=x0
                              -device virtio-blk-device,drive=x0,bus=virtio-mmio-bus.0
                              -nographic -serial mon:stdio -bios none
                              -device virtio-rng-device
                              -device virtio-gpu-device
                              -device virtio-net-device
                              -device virtio-tablet-device
                              -device virtio-keyboard-device
                              -kernel """
